---
- name: Deploy Laravel application to Yandex Cloud
  hosts: 158.160.146.162
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Install Docker using the official script
      shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
      args:
        executable: /bin/bash

    - name: Install docker-compose
      apt:
        name: docker-compose
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Check if Docker container exists
      shell: docker ps -a --filter "name=laravel-project-manager" --format "{{'{{'}}.Names{{'}}'}}"
      register: container_exists

    - name: Stop existing Docker container
      docker_container:
        name: laravel-project-manager
        state: stopped
        force_kill: yes
      when: container_exists.stdout != ""

    - name: Remove existing Docker container
      docker_container:
        name: laravel-project-manager
        state: absent
      when: container_exists.stdout != ""

    - name: Pull the latest Docker image
      docker_image:
        name: dmitriikabatsiura/laravel-project-manager
        tag: latest
        source: pull

    - name: Run the Docker container
      docker_container:
        name: laravel-project-manager
        image: dmitriikabatsiura/laravel-project-manager:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"

    - name: Restart Docker
      service:
        name: docker
        state: restarted